### ISSUE TITLE
Not working NoElytra flag

### ISSUE THREAD

**Issue by SirvydasS** [akdukaan/GriefPreventionFlags#24]
**Describe the bug**
Not working flag NoElytra.

**To Reproduce**
1. Create claim and /setclaimflag NoElytra
2. Try use elytra in claim who should not able fly
3. Player can fly and you see error in console

**Expected behavior**
No error and player should not fly with elytra when is this flag set.

**Versions:**
 - GriefPrevention version 16.18-12-g3d0487d
 - GPFlags version 5.12.0
 - Server version This server is running Paper version git-Paper-40 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 0d79b86)

**Additional context**
ERROR:
<sup>
Could not pass event EntityToggleGlideEvent to GriefPreventionFlags v5.12.0
java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because the return value of "me.ryanhamshire.GriefPrevention.Claim.getOwnerID()" is null
        at me.ryanhamshire.GPFlags.flags.FlagDef_NoElytra.onToggleElytra(FlagDef_NoElytra.java:41) ~[GriefPreventionFlags-5.12.0.jar:?]        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-40]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callToggleGlideEvent(CraftEventFactory.java:1695) ~[paper-1.19.jar:git-Paper-40]                                                                                                                                   at net.minecraft.world.entity.player.Player.startFallFlying(Player.java:1791) ~[?:?]
        at net.minecraft.world.entity.player.Player.tryToStartFallFlying(Player.java:1781) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2622) ~[?:?]        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:17:08 ERROR]: Could not pass event EntityToggleGlideEvent to GriefPreventionFlags v5.12.0
java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because the return value of "me.ryanhamshire.GriefPrevention.Claim.getOwnerID()" is null
        at me.ryanhamshire.GPFlags.flags.FlagDef_NoElytra.onToggleElytra(FlagDef_NoElytra.java:41) ~[GriefPreventionFlags-5.12.0.jar:?]        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-40]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callToggleGlideEvent(CraftEventFactory.java:1695) ~[paper-1.19.jar:git-Paper-40]
        at [net.minecraft.world.entity.LivingEntity.travel](http://net.minecraft.world.entity.livingentity.travel/)(LivingEntity.java:2793) ~[?:?]
        at [net.minecraft.world.entity.player.Player.travel](http://net.minecraft.world.entity.player.player.travel/)(Player.java:1662) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3347) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:561) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2949) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:276) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:675) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:340) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:568) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1581) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-40]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-40]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
</sup>

**Comment by akdukaan** [comment]
Fixed in 5.12.1
